### PR TITLE
chore: use requirements.txt file in generator script to install dependencies

### PR DESCRIPTION
**Pull request by mpeddada1**
`pip install -e generator/` results in the installation of unchecked dependencies. Following the practices in the pip documentation (see https://pip.pypa.io/en/stable/topics/secure-installs/?highlight=no-deps#do-not-use-setuptools-directly), this PR modifies the installation steps to use `--no-deps` to install the generator/ package without deps first. It then calls `pip install --require-hashes -r generator_requirements.txt` to install the dependencies with hash checking.

### CODE REVIEW

**Comment by mpeddada1** [comment]
Logs show:
```The editable requirement file:///tmpfs/src/github/google-api-java-client-services/generator cannot be installed when requiring hashes, because there is no single file to hash.
```

**Comment by meltsufin** [comment]
cc/ @SurferJeffAtGoogle

**Comment by mpeddada1** [comment]
@chingor13 could you help us determine the risks of removing `-e` are? We're thinking of making use of [`requirements.txt` and `--require-hashes`](https://pip.pypa.io/en/stable/reference/requirements-file-format/) when calling `python2 -m pip install -e generator/ --user --require-hashes -r .kokoro/requirements.txt` but it looks like editable installations are incompatible with hash checking.

**Comment by mpeddada1** [comment]
As discussed offline, the generator is not modified elsewhere so will try removing `-e` and applying `--require-hashes`.

**Comment by mpeddada1** [comment]
Now running into: 
```
Collecting pyparsing==3.0.9 (from -r .kokoro/test_requirements.txt (line 52))
  Could not find a version that satisfies the requirement pyparsing==3.0.9 (from -r .kokoro/test_requirements.txt (line 52)) (from versions: 1.4.6, 1.4.7, 1.4.8, 1.4.11, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1.1, 2.4.2a1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7)
```

**Comment by mpeddada1** [comment]
```
Could not find a version that satisfies the requirement rsa==4.9 (from -r .kokoro/test_requirements.txt (line 71)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)
```

**Comment by mpeddada1** [comment]
```
Collecting enum34>=1.1.10; python_version < "3.4" (from google-auth==2.12.0->-r .kokoro/test_requirements.txt (line 25))
Can't verify hashes for these file:// requirements because they point to directories:
    file:///tmpfs/src/github/google-api-java-client-services/generator
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    enum34>=1.1.10; python_version < "3.4" from https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl#sha256=a98a201d6de3f2ab3db284e70a33b0f896fbf35f8086594e8c9e74b909058d53 (from google-auth==2.12.0->-r .kokoro/test_requirements.txt (line 25))
```

**Comment by mpeddada1** [comment]
```
Can't verify hashes for these file:// requirements because they point to directories:
    file:///tmpfs/src/github/google-api-java-client-services/generator
```

**Comment by mpeddada1** [comment]
Installing the generator module through the requirements.txt file results in:
```
Invalid requirement: 'generator==1.4.2     git+https://github.com/googleapis/google-api-java-client-services.git@main#egg=gcp-generator\&subdirectory=generator'
It looks like a path. File 'generator==1.4.2     git+https://github.com/googleapis/google-api-java-client-services.git@main#egg=gcp-generator\&subdirectory=generator' does not exist.
```
The syntax doesn't seem right.

**Comment by mpeddada1** [comment]
Getting a different error:
```
Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    gcp-generator from git+https://github.com/googleapis/google-api-java-client-services.git@main#egg=gcp-generator&subdirectory=generator (from -r .kokoro/test_requirements.txt (line 7))
```

**Comment by mpeddada1** [comment]
Without `python2 -m pip install --require-hashes -r .kokoro/test_requirements.txt --user` we run into ImportErrors:

```
/tmpfs/src/github/google-api-java-client-services /tmpfs/src
Obtaining file:///tmpfs/src/github/google-api-java-client-services/generator
Installing collected packages: google-apis-client-generator
  Running setup.py develop for google-apis-client-generator
Successfully installed google-apis-client-generator
You are using pip version 18.1, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/tmpfs/src/github/google-api-java-client-services/generator /tmpfs/src/github/google-api-java-client-services /tmpfs/src
Traceback (most recent call last):
  File "tests/data_value_test.py", line 19, in <module>
    from google.apputils import basetest
ImportError: No module named apputils
```

**Review by meltsufin — APPROVED** [review]

**Review by aaservice — COMMENTED** [review]
Awesome

**Pull request merged**
